version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    working_dir: /go/src/github.com/souzavitor/go-study
    volumes:
      - .:/go/src/github.com/souzavitor/go-study
    links:
      - "mongo:mongo"
      - "redis:redis"
  mongo:
    image: "mongo:latest"
    volumes:
      - "/docker/data/mongo:/var/lib/mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"