version: '2'
services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    build: .
    working_dir: /go/src/github.com/souzavitor/go-study
    volumes:
      - .:/go/src/github.com/souzavitor/go-study
    environment:
      - VIRTUAL_HOST=short.loc
    links:
      - "mongo:mongo.local"
      - "redis:redis.local"
  mongo:
    image: "mongo:latest"
    volumes:
      - "/docker/data/mongo:/data/db"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"